version: '3'
services:
  backstage:
    image: ${project}-${service}:run
    build:
      context: .
    ports:
      - "3000:3000"
      - "7007:7007"
    volumes:
      - ./backstage:/app
    command: yarn dev

  postgres:
    image: postgres:13
    container_name: postgres-backstage
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: