FROM node:18-bullseye

RUN apt-get update && apt-get install -y \
  python3 \
  build-essential \
  git \
  sqlite3 \
  libsqlite3-dev \
  pkg-config \
  libffi-dev \
  libssl-dev \
  zlib1g-dev \
  g++ \
  make \
  cmake \
  git \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
CMD ["yarn", "dev"]
