version: '3'
services:
  backstage:
    image: punkerside-backstage:run
    build:
      context: .
    ports:
      - "3000:3000"
      - "7007:7007"
    # environment:
    #   NODE_ENV: production
    volumes:
      - ./backstage/app:/app
    command: ["yarn", "start"]
